image: Visual Studio 2017
branches:
  only:
  - master
  - develop
install:
  - cinst gitversion.portable -y
before_build:
  - nuget restore
  - ps: $env:VERSION=$(gitversion /showvariable NuGetVersionV2)
build_script:
  - ps: dotnet restore
  - ps: |
      foreach ($x in dir -Directory src)
      {
        cd src/$x; dotnet setversion $env:VERSION; cd ../..
        dotnet build
        dotnet pack --include-source --include-symbols -c Release -o out/
      }
test_script:
  - ps: |
      foreach ($x in dir -Directory test)
      {
        cd test/$x; dotnet test -c Release
      }
  
artifacts:
  path: '**/*.nupkg'
  name: NuGet packages
deploy:
  provider: NuGet
  skip_symbols: false
  api_key:
    secure: USCwZe1eILJaDmG30VFhlFWmr2P0G6o0HhUau72/W+TzyAMZyqEfL//vQhfjTSKP
  artifact: NuGet packages
  on:
    branch: master